<a href="https://colab.research.google.com/github/NgeZY/data-science-toolkit/blob/main/TutoWeek3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
arr1 = np.array([[1,2],[3,4]])
print(arr1)

[[1 2]
 [3 4]]


In [ ]:
arr2 = np.random.randint(1,10,(3,4))
print(arr2)

[[5 9 3 1]
 [2 7 5 3]
 [5 9 8 8]]


In [ ]:
arr3 = np.ones((2,3))
arr4 = np.zeros((2,3))
print(arr3)
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr5 = np.random.randint(1,100,(6,3))
arr5_T = arr5.T
print(arr5)
print(arr5_T)

[[66 58 30]
 [ 1 42 61]
 [32 38 22]
 [89 82 53]
 [ 2 99 47]
 [45 10 18]]
[[66  1 32 89  2 45]
 [58 42 38 82 99 10]
 [30 61 22 53 47 18]]


In [ ]:
n,p,m = np.random.randint(2,5,size=3)
arr6 = np.random.randint(1,10,(n,p))
arr7 = np.random.randint(1,10,(p,m))
arr8 = arr6@arr7
print(arr8)

[[55 20 50 50]
 [77 28 70 70]
 [37 13 33 31]
 [62 23 57 59]]
